openapi: 3.0.0
info:
  title: learn21 in API
  description: learn
  version: 1.0.0
  contact:
    email: mahdi@gmail.com
    name: mahdi


paths:
  /courses/{id}:
    get:
      summary: Get a course by ID
      description: To fetch details of a course
      operationId: getcourse
      parameters:
        - name: id
          in : path
          description: Id of Course
          required: true
          schema:
            type: integer
          content:
            application/json
      responses:
        "200":
          description: 200 response
          content:
            application/json:
              schema:
                $ref: "#/component/schemas/course"
    /course:
      post:
        description: Use this API to create course
        requestBody:
          description: Structure of a course
          required: true
          content:
            application/json:
              schema:
                $ref: "#/ component/schemas/course"

        responses:
          "200":
            description : 200 response
components:
  schemas:
    course:
      type: object
      properties:
        title:
          type: string
        description:
          type : string
        id:
          type : integer
